name: ShoppingList
environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.15.2
  cloud_firestore: ^5.6.11
  firebase_auth: ^5.6.2
  firebase_auth_web: ^5.15.2