name: ShoppingList
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1  # これを更新！
  cloud_firestore: ^5.6.8 # これを更新！
  firebase_auth: ^5.7.0  # これを更新！
